'use client';

/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import type { StencilReactComponent } from '@stencil/react-output-target/runtime';
import { createComponent } from '@stencil/react-output-target/runtime';
import { MhCalendarDay as MhCalendarDayElement, defineCustomElement as defineMhCalendarDay } from "mh-calendar-core/dist/components/mh-calendar-day.js";
import { MhCalendarEventFull as MhCalendarEventFullElement, defineCustomElement as defineMhCalendarEventFull } from "mh-calendar-core/dist/components/mh-calendar-event-full.js";
import { MhCalendarEventSmall as MhCalendarEventSmallElement, defineCustomElement as defineMhCalendarEventSmall } from "mh-calendar-core/dist/components/mh-calendar-event-small.js";
import { MhCalendarEvent as MhCalendarEventElement, defineCustomElement as defineMhCalendarEvent } from "mh-calendar-core/dist/components/mh-calendar-event.js";
import { MhCalendarHeader as MhCalendarHeaderElement, defineCustomElement as defineMhCalendarHeader } from "mh-calendar-core/dist/components/mh-calendar-header.js";
import { MhCalendarMonth as MhCalendarMonthElement, defineCustomElement as defineMhCalendarMonth } from "mh-calendar-core/dist/components/mh-calendar-month.js";
import { MhCalendarMultiView as MhCalendarMultiViewElement, defineCustomElement as defineMhCalendarMultiView } from "mh-calendar-core/dist/components/mh-calendar-multi-view.js";
import { MhCalendarNavigation as MhCalendarNavigationElement, defineCustomElement as defineMhCalendarNavigation } from "mh-calendar-core/dist/components/mh-calendar-navigation.js";
import { MhCalendarTimeSlots as MhCalendarTimeSlotsElement, defineCustomElement as defineMhCalendarTimeSlots } from "mh-calendar-core/dist/components/mh-calendar-time-slots.js";
import { MhCalendar as MhCalendarElement, defineCustomElement as defineMhCalendar } from "mh-calendar-core/dist/components/mh-calendar.js";
import React from 'react';

export type MhCalendarEvents = NonNullable<unknown>;

export const MhCalendar: StencilReactComponent<MhCalendarElement, MhCalendarEvents> = /*@__PURE__*/ createComponent<MhCalendarElement, MhCalendarEvents>({
    tagName: 'mh-calendar',
    elementClass: MhCalendarElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarEvents,
    defineCustomElement: defineMhCalendar
});

export type MhCalendarDayEvents = NonNullable<unknown>;

export const MhCalendarDay: StencilReactComponent<MhCalendarDayElement, MhCalendarDayEvents> = /*@__PURE__*/ createComponent<MhCalendarDayElement, MhCalendarDayEvents>({
    tagName: 'mh-calendar-day',
    elementClass: MhCalendarDayElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarDayEvents,
    defineCustomElement: defineMhCalendarDay
});

export type MhCalendarEventEvents = NonNullable<unknown>;

export const MhCalendarEvent: StencilReactComponent<MhCalendarEventElement, MhCalendarEventEvents> = /*@__PURE__*/ createComponent<MhCalendarEventElement, MhCalendarEventEvents>({
    tagName: 'mh-calendar-event',
    elementClass: MhCalendarEventElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarEventEvents,
    defineCustomElement: defineMhCalendarEvent
});

export type MhCalendarEventFullEvents = NonNullable<unknown>;

export const MhCalendarEventFull: StencilReactComponent<MhCalendarEventFullElement, MhCalendarEventFullEvents> = /*@__PURE__*/ createComponent<MhCalendarEventFullElement, MhCalendarEventFullEvents>({
    tagName: 'mh-calendar-event-full',
    elementClass: MhCalendarEventFullElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarEventFullEvents,
    defineCustomElement: defineMhCalendarEventFull
});

export type MhCalendarEventSmallEvents = NonNullable<unknown>;

export const MhCalendarEventSmall: StencilReactComponent<MhCalendarEventSmallElement, MhCalendarEventSmallEvents> = /*@__PURE__*/ createComponent<MhCalendarEventSmallElement, MhCalendarEventSmallEvents>({
    tagName: 'mh-calendar-event-small',
    elementClass: MhCalendarEventSmallElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarEventSmallEvents,
    defineCustomElement: defineMhCalendarEventSmall
});

export type MhCalendarHeaderEvents = NonNullable<unknown>;

export const MhCalendarHeader: StencilReactComponent<MhCalendarHeaderElement, MhCalendarHeaderEvents> = /*@__PURE__*/ createComponent<MhCalendarHeaderElement, MhCalendarHeaderEvents>({
    tagName: 'mh-calendar-header',
    elementClass: MhCalendarHeaderElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarHeaderEvents,
    defineCustomElement: defineMhCalendarHeader
});

export type MhCalendarMonthEvents = NonNullable<unknown>;

export const MhCalendarMonth: StencilReactComponent<MhCalendarMonthElement, MhCalendarMonthEvents> = /*@__PURE__*/ createComponent<MhCalendarMonthElement, MhCalendarMonthEvents>({
    tagName: 'mh-calendar-month',
    elementClass: MhCalendarMonthElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarMonthEvents,
    defineCustomElement: defineMhCalendarMonth
});

export type MhCalendarMultiViewEvents = NonNullable<unknown>;

export const MhCalendarMultiView: StencilReactComponent<MhCalendarMultiViewElement, MhCalendarMultiViewEvents> = /*@__PURE__*/ createComponent<MhCalendarMultiViewElement, MhCalendarMultiViewEvents>({
    tagName: 'mh-calendar-multi-view',
    elementClass: MhCalendarMultiViewElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarMultiViewEvents,
    defineCustomElement: defineMhCalendarMultiView
});

export type MhCalendarNavigationEvents = NonNullable<unknown>;

export const MhCalendarNavigation: StencilReactComponent<MhCalendarNavigationElement, MhCalendarNavigationEvents> = /*@__PURE__*/ createComponent<MhCalendarNavigationElement, MhCalendarNavigationEvents>({
    tagName: 'mh-calendar-navigation',
    elementClass: MhCalendarNavigationElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarNavigationEvents,
    defineCustomElement: defineMhCalendarNavigation
});

export type MhCalendarTimeSlotsEvents = NonNullable<unknown>;

export const MhCalendarTimeSlots: StencilReactComponent<MhCalendarTimeSlotsElement, MhCalendarTimeSlotsEvents> = /*@__PURE__*/ createComponent<MhCalendarTimeSlotsElement, MhCalendarTimeSlotsEvents>({
    tagName: 'mh-calendar-time-slots',
    elementClass: MhCalendarTimeSlotsElement,
    // @ts-ignore - ignore potential React type mismatches between the Stencil Output Target and your project.
    react: React,
    events: {} as MhCalendarTimeSlotsEvents,
    defineCustomElement: defineMhCalendarTimeSlots
});
